# Generated by Django 2.1.9 on 2019-10-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20191009_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='seance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
